name: 06 Passing Data Between Steps
on:
  workflow_dispatch:

jobs:
  passing-data-between-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Send Data
        id: data-sender
        run: |
          echo "name=Tegue" >> $GITHUB_OUTPUT
      
      - name: Receive Data
        run: "This is what was outputted in the send data step ${{steps.data-sender.outputs.name}}"
