name: 08 Environment Variables And Secrets
on:
  workflow_dispatch:

jobs:
  using_env_vars_and_secrets:
    runs-on: ubuntu-22.04
    env:
      DEPLOYMENT_ENV: 'production'

    steps:
      - name: Build
        run: |
          echo "Building The Application"
          echo ${{secrets.API_KEY}}
          echo ${{env.DEPLOYMENT_ENV}}
          echo $SECRET_API_KEY
          echo $CONFIG_VARIABLE
          echo $STEPS_USERNAME
          echo ${{ vars.USERNAME }}
        env: 
          SECRET_API_KEY: ${{secrets.API_KEY}}
          STEPS_USERNAME: ${{vars.USERNAME}}
          CONFIG_VARIABLE: ${{env.DEPLOYMENT_ENV}}

      - name: Deploy
        run: |
          # Deploy your application using the secrets and variables
          echo "Global job variable ${{ env.DEPLOYMENT_ENV }}"
          echo "Variable from previous step ${CONFIG_VARIABLE} environment"
          echo "Variable from this step ${CONFIG_VARIABLE2} environment"
          echo "Local step variable ${ANOTHER_VARIABLE}"
          echo "Secret print ${{ secrets.API_KEY }}"
          echo "Step's secret variable ${SECRET_API_KEY}"
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
          CONFIG_VARIABLE2: ${{ env.DEPLOYMENT_ENV }}  # Use a workflow-level environment variable
          ANOTHER_VARIABLE: 'Some value'  # Define a variable directly in the workflow
    
